In [3]:
import numpy as np

# Налаштовуємо кількість символів після коми для естетичного виводу
np.set_printoptions(precision=2, suppress=True)

# Функція для нормалізації зображення до діапазону [0, 1]
def normalize_image(image):
    return image / 255.0

# Створюємо маленьку матрицю (3x3) зі значеннями пікселів від 0 до 255
input_matrix = np.array([
    [34, 87, 123],
    [45, 190, 230],
    [210, 12, 65]
], dtype=np.uint8)

# Нормалізуємо матрицю
normalized_matrix = normalize_image(input_matrix)

# Виводимо вхідні та нормалізовані дані
print("\n\nВхідна матриця:")
print(input_matrix)

print("\nНормалізована матриця:")
print(normalized_matrix)




Вхідна матриця:
[[ 34  87 123]
 [ 45 190 230]
 [210  12  65]]

Нормалізована матриця:
[[0.13 0.34 0.48]
 [0.18 0.75 0.9 ]
 [0.82 0.05 0.25]]
